Error: That port is already in use.
setup_environ
starting thread
setup_environ
[15/May/2009 07:46:54] "GET / HTTP/1.1" 200 50032
[15/May/2009 07:46:54] "GET /static/images/download.gif HTTP/1.1" 304 0
[15/May/2009 07:46:54] "GET /static/images/upload.png HTTP/1.1" 304 0
[15/May/2009 07:46:54] "GET /static/css/site.css HTTP/1.1" 304 0
setup_environ
starting thread
setup_environ
[15/May/2009 07:47:52] "GET / HTTP/1.1" 200 50032
[15/May/2009 07:47:52] "GET /static/images/download.gif HTTP/1.1" 304 0
[15/May/2009 07:47:52] "GET /static/css/site.css HTTP/1.1" 304 0
[15/May/2009 07:47:52] "GET /static/images/upload.png HTTP/1.1" 304 0
setup_environ
starting thread
setup_environ
Error: That port is already in use.
setup_environ
setup_environ
setup_environ
starting thread
setup_environ
[15/May/2009 07:50:43] "GET / HTTP/1.1" 200 50033
[15/May/2009 07:50:43] "GET /static/images/external.png HTTP/1.1" 200 165
[15/May/2009 07:50:43] "GET /static/css/reset-min.css HTTP/1.1" 200 940
[15/May/2009 07:50:43] "GET /static/css/site.css HTTP/1.1" 200 103
[15/May/2009 07:50:43] "GET /static/images/upload.png HTTP/1.1" 200 522
[15/May/2009 07:50:43] "GET /static/images/download.gif HTTP/1.1" 200 189
[15/May/2009 07:50:44] "GET /static/images/download.gif HTTP/1.1" 304 0
[15/May/2009 07:50:44] "GET /static/images/upload.png HTTP/1.1" 304 0
[15/May/2009 07:51:15] "GET / HTTP/1.1" 500 72879
[15/May/2009 07:51:23] "GET / HTTP/1.1" 200 50033
[15/May/2009 07:51:23] "GET /static/css/reset-min.css HTTP/1.1" 200 940
[15/May/2009 07:51:24] "GET /static/images/external.png HTTP/1.1" 200 165
[15/May/2009 07:51:24] "GET /static/images/upload.png HTTP/1.1" 200 522
[15/May/2009 07:51:24] "GET /static/css/site.css HTTP/1.1" 200 103
[15/May/2009 07:51:24] "GET /static/images/download.gif HTTP/1.1" 200 189
setup_environ
setup_environ
setup_environ
setup_environ
setup_environ
setup_environ
setup_environ
setup_environ
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_manager(settings)
  File "/var/lib/python-support/python2.5/django/core/management/__init__.py", line 338, in execute_manager
    setup_environ(settings_mod)
  File "/var/lib/python-support/python2.5/django/core/management/__init__.py", line 316, in setup_environ
    project_module = __import__(project_name, {}, {}, [''])
  File "/home/paul/src/cs682/p3/../p3/__init__.py", line 2, in <module>
    from filesync.models import File
  File "/home/paul/src/cs682/p3/../p3/filesync/models.py", line 1, in <module>
    from django.db import models
  File "/var/lib/python-support/python2.5/django/db/models/__init__.py", line 5, in <module>
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_manager(settings)
  File "/var/lib/python-support/python2.5/django/core/management/__init__.py", line 338, in execute_manager
    setup_environ(settings_mod)
  File "/var/lib/python-support/python2.5/django/core/management/__init__.py", line 316, in setup_environ
    project_module = __import__(project_name, {}, {}, [''])
  File "/home/paul/src/cs682/p3/../p3/__init__.py", line 2, in <module>
    from filesync.models import File
  File "/home/paul/src/cs682/p3/../p3/filesync/models.py", line 1, in <module>
    from django.db import models
  File "/var/lib/python-support/python2.5/django/db/models/__init__.py", line 5, in <module>
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_manager(settings)
  File "/var/lib/python-support/python2.5/django/core/management/__init__.py", line 338, in execute_manager
    setup_environ(settings_mod)
  File "/var/lib/python-support/python2.5/django/core/management/__init__.py", line 316, in setup_environ
    project_module = __import__(project_name, {}, {}, [''])
  File "/home/paul/src/cs682/p3/../p3/__init__.py", line 2, in <module>
    from filesync.models import File
  File "/home/paul/src/cs682/p3/../p3/filesync/models.py", line 1, in <module>
    from django.db import models
  File "/var/lib/python-support/python2.5/django/db/models/__init__.py", line 5, in <module>
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_manager(settings)
  File "/var/lib/python-support/python2.5/django/core/management/__init__.py", line 338, in execute_manager
    setup_environ(settings_mod)
  File "/var/lib/python-support/python2.5/django/core/management/__init__.py", line 316, in setup_environ
    project_module = __import__(project_name, {}, {}, [''])
  File "/home/paul/src/cs682/p3/../p3/__init__.py", line 2, in <module>
    from filesync.models import File
  File "/home/paul/src/cs682/p3/../p3/filesync/models.py", line 1, in <module>
    from django.db import models
  File "/var/lib/python-support/python2.5/django/db/models/__init__.py", line 5, in <module>
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_manager(settings)
  File "/var/lib/python-support/python2.5/django/core/management/__init__.py", line 338, in execute_manager
    setup_environ(settings_mod)
  File "/var/lib/python-support/python2.5/django/core/management/__init__.py", line 316, in setup_environ
    project_module = __import__(project_name, {}, {}, [''])
  File "/home/paul/src/cs682/p3/../p3/__init__.py", line 2, in <module>
    from filesync.models import File
  File "/home/paul/src/cs682/p3/../p3/filesync/models.py", line 1, in <module>
    from django.db import models
  File "/var/lib/python-support/python2.5/django/db/models/__init__.py", line 5, in <module>
    from django.db.models.query import Q
  File "/var/lib/python-support/python2.5/django/db/models/query.py", line 7, in <module>
    from django.db.models.fields import DateField
  File "/var/lib/python-support/python2.5/django/db/models/fields/__init__.py", line 16, in <module>
    from django.db.models.query import Q
  File "/var/lib/python-support/python2.5/django/db/models/query.py", line 7, in <module>
    from django.db.models.fields import DateField
  File "/var/lib/python-support/python2.5/django/db/models/fields/__init__.py", line 16, in <module>
    from django.db.models.query import Q
  File "/var/lib/python-support/python2.5/django/db/models/query.py", line 7, in <module>
    from django.db.models.fields import DateField
  File "/var/lib/python-support/python2.5/django/db/models/fields/__init__.py", line 16, in <module>
    from django.db.models.query import Q
  File "/var/lib/python-support/python2.5/django/db/models/query.py", line 7, in <module>
    from django.db.models.fields import DateField
  File "/var/lib/python-support/python2.5/django/db/models/fields/__init__.py", line 16, in <module>
    from django.db.models.query import Q
  File "/var/lib/python-support/python2.5/django/db/models/query.py", line 7, in <module>
    from django.db.models.fields import DateField
  File "/var/lib/python-support/python2.5/django/db/models/fields/__init__.py", line 16, in <module>
    from django import forms
  File "/var/lib/python-support/python2.5/django/forms/__init__.py", line 13, in <module>
    from django import forms
  File "/var/lib/python-support/python2.5/django/forms/__init__.py", line 13, in <module>
    from django import forms
  File "/var/lib/python-support/python2.5/django/forms/__init__.py", line 15, in <module>
    from django import forms
  File "/var/lib/python-support/python2.5/django/forms/__init__.py", line 15, in <module>
    from django import forms
  File "/var/lib/python-support/python2.5/django/forms/__init__.py", line 14, in <module>
    from util import ValidationError
  File "/var/lib/python-support/python2.5/django/forms/util.py", line 1, in <module>
    from util import ValidationError
  File "/var/lib/python-support/python2.5/django/forms/util.py", line 1, in <module>
    from fields import *
  File "/var/lib/python-support/python2.5/django/forms/fields.py", line 32, in <module>
    from fields import *
    from django.utils.html import conditional_escape
  File "/var/lib/python-support/python2.5/django/utils/html.py", line 18, in <module>
    from django.core.files.uploadedfile import SimpleUploadedFile as UploadedFile
  File "/var/lib/python-support/python2.5/django/core/files/uploadedfile.py", line 13, in <module>
    from widgets import *
  File "/var/lib/python-support/python2.5/django/forms/widgets.py", line 3, in <module>
    from django.utils.html import conditional_escape
  File "/var/lib/python-support/python2.5/django/utils/html.py", line 26, in <module>
  File "/var/lib/python-support/python2.5/django/forms/fields.py", line 32, in <module>
    from django.core.files.uploadedfile import SimpleUploadedFile as UploadedFile
  File "/var/lib/python-support/python2.5/django/core/files/uploadedfile.py", line 3, in <module>
    """
KeyboardInterrupt
    """
KeyboardInterrupt
    unencoded_ampersands_re = re.compile(r'&(?!(\w+|#\d+);)')
  File "/usr/lib/python2.5/re.py", line 188, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.5/re.py", line 239, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python2.5/sre_compile.py", line 507, in compile
    hard_coded_bullets_re = re.compile(r'((?:<p>(?:%s).*?[a-zA-Z].*?</p>\s*)+)' % '|'.join([re.escape(x) for x in DOTS]), re.DOTALL)
  File "/usr/lib/python2.5/re.py", line 188, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.5/re.py", line 239, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python2.5/sre_compile.py", line 507, in compile
    from django.core.files import temp as tempfile
  File "/var/lib/python-support/python2.5/django/core/files/temp.py", line 13, in <module>
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python2.5/sre_parse.py", line 681, in parse
    tail = source.get()
  File "/usr/lib/python2.5/sre_parse.py", line 209, in get
    self.__next()
  File "/usr/lib/python2.5/sre_parse.py", line 189, in __next
    if self.index >= len(self.string):
KeyboardInterrupt
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python2.5/sre_parse.py", line 679, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python2.5/sre_parse.py", line 314, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python2.5/sre_parse.py", line 639, in _parse
    p = _parse_sub(source, state)
  File "/usr/lib/python2.5/sre_parse.py", line 314, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python2.5/sre_parse.py", line 639, in _parse
    p = _parse_sub(source, state)
  File "/usr/lib/python2.5/sre_parse.py", line 314, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python2.5/sre_parse.py", line 640, in _parse
    if not sourcematch(")"):
    import tempfile
  File "/usr/lib/python2.5/tempfile.py", line 18, in <module>
    """
KeyboardInterrupt
  File "/usr/lib/python2.5/sre_parse.py", line 201, in match
    def match(self, char, skip=1):
KeyboardInterrupt
[15/May/2009 10:04:58] "GET / HTTP/1.1" 200 50041
[15/May/2009 10:04:58] "GET /static/images/download.gif HTTP/1.1" 304 0
[15/May/2009 10:04:58] "GET /static/css/site.css HTTP/1.1" 304 0
[15/May/2009 10:04:58] "GET /static/images/upload.png HTTP/1.1" 304 0
setup_environ
setup_environ
setup_environ
setup_environ
Validating models...
0 errors found

Django version 1.0.2 final, using settings 'p3.settings'
Development server is running at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
setup_environ
setup_environ
Validating models...
0 errors found

Django version 1.0.2 final, using settings 'p3.settings'
Development server is running at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[15/May/2009 10:06:04] "GET / HTTP/1.1" 200 50041
[15/May/2009 10:06:04] "GET /static/images/download.gif HTTP/1.1" 304 0
[15/May/2009 10:06:04] "GET /static/css/site.css HTTP/1.1" 304 0
[15/May/2009 10:06:04] "GET /static/images/upload.png HTTP/1.1" 304 0
setup_environ
setup_environ
setup_environ
setup_environ
Validating models...
0 errors found

Django version 1.0.2 final, using settings 'p3.settings'
Development server is running at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
setup_environ
setup_environ
Validating models...
0 errors found

Django version 1.0.2 final, using settings 'p3.settings'
Development server is running at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[15/May/2009 10:06:47] "GET / HTTP/1.1" 200 50041
[15/May/2009 10:06:47] "GET /static/css/site.css HTTP/1.1" 304 0
[15/May/2009 10:06:47] "GET /static/images/download.gif HTTP/1.1" 304 0
[15/May/2009 10:06:48] "GET /static/images/upload.png HTTP/1.1" 304 0
[15/May/2009 10:15:43] "GET / HTTP/1.1" 200 50041
[15/May/2009 10:15:43] "GET /static/css/reset-min.css HTTP/1.1" 200 940
[15/May/2009 10:15:43] "GET /static/css/site.css HTTP/1.1" 200 103
[15/May/2009 10:15:43] "GET /static/images/upload.png HTTP/1.1" 200 522
[15/May/2009 10:15:43] "GET /static/images/download.gif HTTP/1.1" 200 189
[15/May/2009 10:15:43] "GET /static/images/external.png HTTP/1.1" 200 165
setup_environ
setup_environ
Validating models...
0 errors found

Django version 1.0.2 final, using settings 'p3.settings'
Development server is running at http://0.0.0.0:8001/
Quit the server with CONTROL-C.
setup_environ
setup_environ
Validating models...
0 errors found

Django version 1.0.2 final, using settings 'p3.settings'
Development server is running at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
